/*
 * generated by Xtext 2.26.0
 */
package nl.tue.robotsupervisorycontrollerdsl.formatting2

import org.eclipse.xtext.formatting2.AbstractFormatter2
import org.eclipse.xtext.formatting2.IFormattableDocument
import nl.tue.robotsupervisorycontrollerdsl.robotSupervisoryControllerDSL.Base

class RobotSupervisoryControllerDSLFormatter extends AbstractFormatter2 {

	def dispatch void format(Base model, extension IFormattableDocument document) {

	}
	
}
