/*
 * generated by Xtext 2.26.0
 */
package nl.tue.robotsupervisorycontrollerdsl.ide;


/**
 * Use this class to register ide components.
 */
public class RobotSupervisoryControllerDSLIdeModule extends AbstractRobotSupervisoryControllerDSLIdeModule {
}
