/*
 * generated by Xtext 2.26.0
 */
package nl.tue.robotsupervisorycontrollerdsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import nl.tue.robotsupervisorycontrollerdsl.RobotSupervisoryControllerDSLRuntimeModule;
import nl.tue.robotsupervisorycontrollerdsl.RobotSupervisoryControllerDSLStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class RobotSupervisoryControllerDSLIdeSetup extends RobotSupervisoryControllerDSLStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new RobotSupervisoryControllerDSLRuntimeModule(), new RobotSupervisoryControllerDSLIdeModule()));
	}
	
}
