/*
 * generated by Xtext 2.26.0
 */
package nl.tue.robotsupervisorycontrollerdsl;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class RobotSupervisoryControllerDSLRuntimeModule extends AbstractRobotSupervisoryControllerDSLRuntimeModule {
}
