/*
 * generated by Xtext 2.26.0
 */
package nl.tue.robotsupervisorycontrollerdsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class RobotSupervisoryControllerDSLStandaloneSetup extends RobotSupervisoryControllerDSLStandaloneSetupGenerated {

	public static void doSetup() {
		new RobotSupervisoryControllerDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
