/*
 * generated by Xtext 2.26.0
 */
package nl.tue.robotsupervisorycontrollerdsl.validation;

import org.eclipse.xtext.validation.ComposedChecks;

import nl.tue.robotsupervisorycontrollerdsl.validation.rules.CorrectDataProvisioningRule;
import nl.tue.robotsupervisorycontrollerdsl.validation.rules.CorrectResultTypeRule;
import nl.tue.robotsupervisorycontrollerdsl.validation.rules.NoAssignmentOnMessagesToNodeRule;
import nl.tue.robotsupervisorycontrollerdsl.validation.rules.NoAssignmentOutsideScopeRule;
import nl.tue.robotsupervisorycontrollerdsl.validation.rules.SingleComponentBehaviourRule;
import nl.tue.robotsupervisorycontrollerdsl.validation.rules.SingleDefaultEnumRule;
import nl.tue.robotsupervisorycontrollerdsl.validation.rules.SingleInitialStateRule;
import nl.tue.robotsupervisorycontrollerdsl.validation.rules.UniqueCommunicationTypeNameRule;
import nl.tue.robotsupervisorycontrollerdsl.validation.rules.UniqueDataTypeNameRule;
import nl.tue.robotsupervisorycontrollerdsl.validation.rules.UniqueStateNameRule;

@ComposedChecks(validators = {
		SingleInitialStateRule.class,
		UniqueCommunicationTypeNameRule.class,
		UniqueDataTypeNameRule.class,
		UniqueStateNameRule.class,
		SingleComponentBehaviourRule.class,
		SingleDefaultEnumRule.class,
		NoAssignmentOnMessagesToNodeRule.class,
		NoAssignmentOutsideScopeRule.class,
		CorrectResultTypeRule.class,
		CorrectDataProvisioningRule.class,
})
public class RobotSupervisoryControllerDSLValidator extends AbstractRobotSupervisoryControllerDSLValidator {
}
