/*
 * generated by Xtext 2.26.0
 */
package nl.tue.robotsupervisorycontrollerdsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class RobotSupervisoryControllerDSLUiModule extends AbstractRobotSupervisoryControllerDSLUiModule {

	public RobotSupervisoryControllerDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
