name: Continuous Integration

on:
  push:
    branches:
    - main

jobs:
  build-vscode-extension:
    name: Build Visual Studio Code extension
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: stCarolas/setup-maven@v4.3
      with:
        maven-version: 3.8.4
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'
        cache: 'maven' # Maven cache is used for building CIF
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
    - run: ./gradlew build
      working-directory: language/
    - run: yarn && yarn package
      working-directory: extension/
    - uses: actions/upload-artifact@v3
      with:
        name: vscode-extension
        path: extension/robot-supervisory-controller-dsl-*.vsix 