name: Continuous Integration

on:
  push:
    branches:
    - main
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-vscode-extension:
    name: Build Visual Studio Code extension
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: stCarolas/setup-maven@v4.3
      with:
        maven-version: 3.8.4
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'
        cache: 'maven' # Maven cache is used for building CIF
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
    - run: ./gradlew build
      working-directory: language/
    - run: yarn && yarn package
      working-directory: extension/
    - uses: actions/upload-artifact@v3
      with:
        name: vscode-extension
        path: extension/robot-supervisory-controller-dsl-*.vsix

  build-eclipse-plugin:
    name: Build Eclipse plugin
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: stCarolas/setup-maven@v4.3
      with:
        maven-version: 3.8.4
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'
        cache: 'maven' # Maven cache is used for building CIF
    - run: |-
        gradle build
        gradle jar
      name: Build Escet
      working-directory: language/nl.tue.robotsupervisorycontrollerdsl.cifwrapper
    - name: Copy libraries
      run: |-
        mkdir -p language/nl.tue.robotsupervisorycontrollerdsl/libs/
        cp language/nl.tue.robotsupervisorycontrollerdsl.cifwrapper/build/libs/escet-wrapper.jar language/nl.tue.robotsupervisorycontrollerdsl/libs/escet-wrapper.jar
    - run: rm -rf ~/.m2/repository/.meta/p2-artifacts.properties
      name: Fix corrupt cache
    - run: mvn package
      working-directory: language/
    - uses: actions/upload-artifact@v3
      with:
        name: eclipse-updatesite
        path: language/nl.tue.robotsupervisorycontrollerdsl.updatesite/target/nl.tue.robotsupervisorycontrollerdsl.updatesite-*.zip

  create-release:
    name: Create release
    runs-on: ubuntu-latest
    needs: [build-vscode-extension, build-eclipse-plugin]
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write
    steps:
    - uses: actions/download-artifact@v3
      with:
        path: artifacts/
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "artifacts/eclipse-updatesite/*.zip,artifacts/vscode-extension/*.vsix"
        omitBody: true
        generateReleaseNotes: true
        removeArtifacts: true
        allowUpdates: true
        token: ${{ secrets.GITHUB_TOKEN }}